api_username='ampel-bot'
api_key='very large Discourse API KEY'
forum_address='https://forum.discourse.adress.com'
forum_calender= 'https://forum.discourse.adress.com/c/veranstaltungen/l/calendar'
content_red = "[X] :red_square: keiner da\n[ ] :green_heart: jemand da\n\n<datetimestring_ampel>\n\n[zum Veranstaltungs-Kalender](https://forum.discourse.adress.com/c/veranstaltungen/l/calendar)\n|||||\n-|-|-|-\nF7 | Dj-Pult | <F7> | <datetimestring_f7>\nF13 | Kasse | <F13> | <datetimestring_f13>\nF15 | Bartheke Licht | <F15> | <datetimestring_f15>"
content_grn = "[ ] :red_square: keiner da\n[X] :green_heart: jemand da\n\n<datetimestring_ampel>\n\n[zum Veranstaltungs-Kalender](https://forum.discourse.adress.com/c/veranstaltungen/l/calendar)\n|||||\n-|-|-|-\nF7 | Dj-Pult | <F7> | <datetimestring_f7>\nF13 | Kasse | <F13> | <datetimestring_f13>\nF15 | Bartheke Licht | <F15> | <datetimestring_f15>"
post_id = 28410
# topic_id = 3533     #nur für Update Zeitstempel, noch nicht implementiert
edit_reason = "Ampel-Bot"
